config/routes.rb
Rails.application.routes.draw do 
  root 'notes#index'
  resources :notes, except: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
  end

  def new
  	@note = Note.new
  end 

  def create
  	Note.create(note_params)
  	redirect_to notes_path
  end 

  def edit 
    @note = Note.find(params[:id])
  end 

  def update 
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to edit_note_path(@note)
    end
  end 

  private 

  def note_params
  	params.require(:note).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BigNote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>

<div>
    <%= f.label :title %>
   	<%= f.text_field :title%>
</div>
<div>
    <%= f.label :body %>
   	<%= f.text_area :body, data: { provider: 'summernote' }%>
</div>

<%= f.submit 'save' %>
<%= link_to 'close', notes_path %>

<% end %>

app/views/notes/edit.html.erb
<h1>edit</h1>

<%= render 'form' %>

app/views/notes/index.html.erb
<h1> HELLLO YEH </h1>
<%= link_to 'New Note', new_note_path %>

<% if @notes.any? %>
	<ul>
		<% @notes.each do |note| %>
			<li> <%= link_to note.title, edit_note_path(note) %> </li>
		<% end %>
	</ul>
<% end %>

app/views/notes/new.html.erb
<h1>new</h1>

<%= render 'form' %>